# information for application name and launcher
Application:

  name: app-tools
  asciibanner: src-legacy/assets/asciibanner-VA.txt
  icon: src-legacy/assets/autoactuary.ico
  installdir: '%localappdata%\autoactuary\app-tools'

  pause: 1

  programdata:
    - [ ./bin/python, ./bin/python ]
    - [ ./bin/7z.dll, ./bin/7z.dll ]
    - [ ./bin/7z.exe, ./bin/7z.exe ]
    - [ ./bin/git, ./bin/git       ]

    - [ ./cli, ./cli               ]
    - [ ./src-legacy, ./src-legacy ]
    - [ ./app_tools, ./app_tools   ]

Dependencies:
  deploy-scripts: d8ac2c6
