[mypy]
python_version = 3.11
strict = true
exclude = (?x)(
    ^app_builder/(app_builder__.*|create_.*|get_dependencies\.py|file_pattern_7zip\.py|git_revision\.py|paths\.py|run_and_suppress\.py|shell\.py|scripts\.py|util\.py|errors\.py)$
    | ^app_builder/commands/.*
    | ^test/__init__\.py$
)
