# fmt: off
[mypy]
python_version = 3.11
strict = true
files = app_builder/__init__.py, app_builder/__main__.py, app_builder/main.py, app_builder/schema.py, app_builder/schema_core.py, app_builder/schema_export.py, app_builder/config.py, app_builder/pydantic_models.py, app_builder/project.py, app_builder/fileset.py, app_builder/hooks.py, app_builder/poetry_dependencies.py, app_builder/python_runtime.py, app_builder/exewrap.py, app_builder/installer_bundle.py, app_builder/build.py, app_builder/template.py, test/test_config.py, test/test_schema_core.py, test/test_schema_export.py, test/test_template.py, test/test_end_to_end.py, test/test_poetry_dependencies.py, test/test_python_runtime.py, test/test_hooks.py, test/test_build_hooks.py, test/test_installer_bundle.py
# fmt: on
